### ISSUE TITLE
Replacement for DK-USB-SPI-10225

### ISSUE THREAD

**Issue by jvelazqueztraut** [lorf/csr-spi-ftdi#15]
Would this firmware flashed in an FTDI be a potential replacement for CSR's USB SPI flasher?
I'm currently buying these modules to flash CSR1010 chips, but they seem to be really fragile, not well protected and I've already burned quite a lot of them. This is why such a replacemente would be ideal.
Sorry to be asking this as an issue, but I couldn't find a discussion board on this repo.
Thanks in advance!

**Comment by lorf** [comment]
Well, I can't say if it's on par with CSR's SPI programmer, since I don't own one, but it works well enough for amateur needs like occasionally reflash the firmware or fiddle with PS keys. It may be slow for professional needs, but again, I don't know for sure. Also at the moment it supports only one programmer connected, so no broadcast mode.

Let me know if You give it a try, thanks!
