### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Fireflaker** [lorf/csr-spi-ftdi#20]
Does it work for CSR8645 and CSRA64215? Will it work with a USB to TTL converter or even an arduino?

**Comment by lorf** [comment]
Yes, it works with CSR8645 and should work with CSRA64215. No, it only
works with FTDI USB-UART converter chips, see "related projects" in readme
for other options.

13 мая 2017 г. 1:37 пользователь "Fireflaker" <notifications@github.com>
написал:

Does it work for CSR8645 and CSRA64215? Will it work with a USB to TTL
converter or even an arduino?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lorf/csr-spi-ftdi/issues/20>, or mute the thread

**Comment by Fireflaker** [comment]
Thank you very much!
lorf <notifications@github.com>于2017年5月12日 周五下午10:58写道：
